import { Component } from '@angular/core';
import { CarouselComponent, carouselProps, movie } from '../carousel/carousel.component';

@Component({
  selector: 'app-search',
  imports: [CarouselComponent],
  templateUrl: './search.component.html',
  styleUrl: './search.component.css'
})
export class SearchComponent {
public defaultMovies : movie[] = [
    { id: (1).toString(), name: 'Movie Name', link: ''},
    { id: (2).toString(), name: 'Movie Name', link: ''},
    { id: (3).toString(), name: 'Movie Name', link: ''},
    { id: (4).toString(), name: 'Movie Name', link: ''},
    { id: (5).toString(), name: 'Movie Name', link: ''},
    { id: (6).toString(), name: 'Movie Name', link: ''},
    { id: (7).toString(), name: 'Movie Name', link: ''},
    { id: (8).toString(), name: 'Movie Name', link: ''},
    { id: (9).toString(), name: 'Movie Name', link: ''},
    { id: (10).toString(), name: 'Movie Name', link: ''},
    { id: (11).toString(), name: 'Movie Name', link: ''},
    { id: (12).toString(), name: 'Movie Name', link: ''},
    { id: (13).toString(), name: 'Movie Name', link: ''},
    { id: (14).toString(), name: 'Movie Name', link: ''},
    { id: (15).toString(), name: 'Movie Name', link: ''},
    { id: (16).toString(), name: 'Movie Name', link: ''},
    { id: (17).toString(), name: 'Movie Name', link: ''},
    { id: (18).toString(), name: 'Movie Name', link: ''},
    { id: (19).toString(), name: 'Movie Name', link: ''},
    { id: (20).toString(), name: 'Movie Name', link: ''},
    { id: (31).toString(), name: 'Movie Name', link: ''},
    { id: (32).toString(), name: 'Movie Name', link: ''},
    { id: (33).toString(), name: 'Movie Name', link: ''},
    { id: (34).toString(), name: 'Movie Name', link: ''},
    { id: (35).toString(), name: 'Movie Name', link: ''},
    { id: (36).toString(), name: 'Movie Name', link: ''},
    { id: (37).toString(), name: 'Movie Name', link: ''},
    { id: (38).toString(), name: 'Movie Name', link: ''},
    { id: (39).toString(), name: 'Movie Name', link: ''},
    { id: (40).toString(), name: 'Movie Name', link: ''},
    { id: (41).toString(), name: 'Movie Name', link: ''},
    { id: (42).toString(), name: 'Movie Name', link: ''},
    { id: (43).toString(), name: 'Movie Name', link: ''},
    { id: (44).toString(), name: 'Movie Name', link: ''},
    { id: (45).toString(), name: 'Movie Name', link: ''},
    { id: (46).toString(), name: 'Movie Name', link: ''},
    { id: (47).toString(), name: 'Movie Name', link: ''},
    { id: (48).toString(), name: 'Movie Name', link: ''},
    { id: (49).toString(), name: 'Movie Name', link: ''},
    { id: (50).toString(), name: 'Movie Name', link: ''},
    { id: (51).toString(), name: 'Movie Name', link: ''},
    { id: (52).toString(), name: 'Movie Name', link: ''},
    { id: (53).toString(), name: 'Movie Name', link: ''},
    { id: (54).toString(), name: 'Movie Name', link: ''},
    { id: (55).toString(), name: 'Movie Name', link: ''},
    { id: (56).toString(), name: 'Movie Name', link: ''},
    { id: (57).toString(), name: 'Movie Name', link: ''},
    { id: (58).toString(), name: 'Movie Name', link: ''},
    { id: (59).toString(), name: 'Movie Name', link: ''},
    { id: (60).toString(), name: 'Movie Name', link: ''},
    { id: (61).toString(), name: 'Movie Name', link: ''},
    { id: (62).toString(), name: 'Movie Name', link: ''},
    { id: (63).toString(), name: 'Movie Name', link: ''},
    { id: (64).toString(), name: 'Movie Name', link: ''},
    { id: (65).toString(), name: 'Movie Name', link: ''},
    { id: (66).toString(), name: 'Movie Name', link: ''},
    { id: (67).toString(), name: 'Movie Name', link: ''},
    { id: (68).toString(), name: 'Movie Name', link: ''},
    { id: (69).toString(), name: 'Movie Name', link: ''},
    { id: (70).toString(), name: 'Movie Name', link: ''},
  ]
}
