import { Component } from '@angular/core';
import { CarouselComponent, carouselProps, movie } from '../carousel/carousel.component';

@Component({
  selector: 'app-search',
  imports: [CarouselComponent],
  templateUrl: './search.component.html',
  styleUrl: './search.component.css'
})
export class SearchComponent {
public defaultMovies : movie[] = [
    { id: 1, name: 'Movie Name', link: ''},
    { id: 2, name: 'Movie Name', link: ''},
    { id: 3, name: 'Movie Name', link: ''},
    { id: 4, name: 'Movie Name', link: ''},
    { id: 5, name: 'Movie Name', link: ''},
    { id: 6, name: 'Movie Name', link: ''},
    { id: 7, name: 'Movie Name', link: ''},
    { id: 8, name: 'Movie Name', link: ''},
    { id: 9, name: 'Movie Name', link: ''},
    { id: 10, name: 'Movie Name', link: ''},
    { id: 11, name: 'Movie Name', link: ''},
    { id: 12, name: 'Movie Name', link: ''},
    { id: 13, name: 'Movie Name', link: ''},
    { id: 14, name: 'Movie Name', link: ''},
    { id: 15, name: 'Movie Name', link: ''},
    { id: 16, name: 'Movie Name', link: ''},
    { id: 17, name: 'Movie Name', link: ''},
    { id: 18, name: 'Movie Name', link: ''},
    { id: 19, name: 'Movie Name', link: ''},
    { id: 20, name: 'Movie Name', link: ''},
    { id: 31, name: 'Movie Name', link: ''},
    { id: 32, name: 'Movie Name', link: ''},
    { id: 33, name: 'Movie Name', link: ''},
    { id: 34, name: 'Movie Name', link: ''},
    { id: 35, name: 'Movie Name', link: ''},
    { id: 36, name: 'Movie Name', link: ''},
    { id: 37, name: 'Movie Name', link: ''},
    { id: 38, name: 'Movie Name', link: ''},
    { id: 39, name: 'Movie Name', link: ''},
    { id: 40, name: 'Movie Name', link: ''},
    { id: 41, name: 'Movie Name', link: ''},
    { id: 42, name: 'Movie Name', link: ''},
    { id: 43, name: 'Movie Name', link: ''},
    { id: 44, name: 'Movie Name', link: ''},
    { id: 45, name: 'Movie Name', link: ''},
    { id: 46, name: 'Movie Name', link: ''},
    { id: 47, name: 'Movie Name', link: ''},
    { id: 48, name: 'Movie Name', link: ''},
    { id: 49, name: 'Movie Name', link: ''},
    { id: 50, name: 'Movie Name', link: ''},
    { id: 51, name: 'Movie Name', link: ''},
    { id: 52, name: 'Movie Name', link: ''},
    { id: 53, name: 'Movie Name', link: ''},
    { id: 54, name: 'Movie Name', link: ''},
    { id: 55, name: 'Movie Name', link: ''},
    { id: 56, name: 'Movie Name', link: ''},
    { id: 57, name: 'Movie Name', link: ''},
    { id: 58, name: 'Movie Name', link: ''},
    { id: 59, name: 'Movie Name', link: ''},
    { id: 60, name: 'Movie Name', link: ''},
    { id: 61, name: 'Movie Name', link: ''},
    { id: 62, name: 'Movie Name', link: ''},
    { id: 63, name: 'Movie Name', link: ''},
    { id: 64, name: 'Movie Name', link: ''},
    { id: 65, name: 'Movie Name', link: ''},
    { id: 66, name: 'Movie Name', link: ''},
    { id: 67, name: 'Movie Name', link: ''},
    { id: 68, name: 'Movie Name', link: ''},
    { id: 69, name: 'Movie Name', link: ''},
    { id: 70, name: 'Movie Name', link: ''},
  ]
}
